logging:
    config: classpath:logback-spring.xml
mybatis:
    configuration:
        map-underscore-to-camel-case: true
    mapper-locations: classpath:mappers/*.xml
    type-aliases-package: com.hmc.his.model
pulsar:
    url: host.docker.internal:6650
spring:
    security:
        user:
            name: admin
            password: admin
            roles: ADMIN
    data:
        redis:
            connect-timeout: 5s
            database: 0
            host: host.docker.internal
            port: 4379
            timeout: 5s
    datasource:
        password: pkq210210
        url: jdbc:mysql://host.docker.internal:3306/his?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
        username: root
    profiles:
        active: prod
server:
    port: 81