pulsar:
  url: localhost:6650
logging:
  config: classpath:logback-spring.xml
spring:
  data:
    redis:
      host: localhost
      port: 4379
      database: 1
      connect-timeout: 5s
      timeout: 5s
  datasource:
    username: root
    password: pkq210210
    url: jdbc:mysql://localhost:3306/his_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.hmc.his.model
server:
  port: 8001